version: '3.1'

services:

  db:
    image: mysql:5.7
    volumes:
      - wptut:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: 8090pure100 # default USER is root

  wordpress:
    build: ./wordpress
    volumes:
      - ./wp-content:/var/www/html/wp-content
    ports:
      - 80:80

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    depends_on:
      - db
    restart: always
    ports:
      - 8080:80
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: 8090pure100

volumes:
  wptut:
